/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ConfidentialVoting__factory } from "./ConfidentialVoting__factory";
export { SimpleVoting__factory } from "./SimpleVoting__factory";
