/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ConfidentialVoting } from "./ConfidentialVoting";
export type { SimpleVoting } from "./SimpleVoting";
